changelog:
  exclude:
    labels:
      - chore
      - ci
      - duplicate
      - good first issue
      - help wanted
      - invalid
      - question
      - revert
      - spike
      - style
      - test
      - wontfix
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - change
    - title: Deprecated
      labels:
        - deprecate
    - title: Removed
      labels:
        - remove
    - title: Fixed
      labels:
        - bug
    - title: security
      labels:
        - security
