# Copyright 2025 Michael F. Collins, III
#
# Time Source-Available Temporary License (v0.1)
#
# IMPORTANT: This is a source-available license and is not an open source
# license. The rights granted below are limited, temporary, and subject to
# change upon a future commercial release of the software.
#
# 1. Definitions
#
# - "Software" means the Time product, including its source code, build
#   scripts, configuration, and associated assets contained in this
#   repository.
# - "Derivative Works" means any work based upon the Software, including
#   modifications, adaptations, enhancements, or other works that are based on
#   or incorporate the Software, in whole or in part.
# - "Internal Use" means use by an individual or within a single legal entity
#   (including its employees and contractors acting on its behalf) for its own
#   business or personal operations, and not for providing the Software or any
#   substantial part of it to any third party as a hosted service, product, or
#   commercial offering.
# - "Integrations and Extensions" means separately distributed modules,
#   plugins, connectors, or tools that interact with the Software through
#   documented interfaces, data formats, or APIs, but which are not a
#   substantial copy of the Software itself.
# - "Commercial Release" means a future releaase of the Software made
#   available by the copyright holder under a different license, including a
#   commercial license.
#
# 2. License Grant (Temporary, Source-Available)
#
# Subject to the terms and conditions of this License, the copyright holder
# grants you a limited, non-exclusive, non-transferable, revocable license to:
#
# - Read and inspect the source code to learn how the Software is built and
#   understand the underlying technology (educational use);
# - Use, compile, and run the Software for your Internal Use;
# - Create Derivative Works of the Software for your Internal Use;
# - Develop Integrations and Extensions that interface with the Software;
# - Share your Derivative Works with other individuals or organizations solely
#   for their Internal Use, provided that (a) you and the recipient do not
#   charge any fees or other consideration for such Derivative Works or their
#   use, (b) you include this License and all applicable copyright notices
#   with any distribution, and (c) the recipient is bound by terms no less
#   protective of the Software and the copyright holder than these.
#
# This License is temporary and remains in effect only until the Commercial
# Release, as described below.
#
# 3. Restrictions
#
# Except as expressly permitted above, you may not:
#
# - Use the Software, Derivative Works, or Integration and Extensions for any
#   commercial purpose, including selling access, offering as-a-service
#   (SaaS), charging for hosting, support, or distribution, or otherwise
#   monetizing the Software or Derivative Works;
# - Distribute the Software or Derivative Works to the public for general use,
#   whether free or paid, other than sharing Derivative Works solely for a
#   recipient's Internal Use as allowed above;
# - Re-license, sublicense, or otherwise transfer rights in the Software,
#   except as expressly allowed herein;
# - Remove, alter, or obscure any copyright, license, or attribution notices;
# - Use the Software, trademarks, logos, or trade dress of the Time product or
#   the copyright holder in any way that suggests endorsement or affiliation
#   without prior written permission;
# - Use the Software to create a substantially similar competing product that
#   you distribute or offer to others.
#
# 4. Future Commercial License Requirement (Temporary Nature)
#
# This License is a temporary license intended to make the Software source
# available for learning, evaluation, and development of Integrations and
# Extensions prior to a commercial offering. Upon the Commercial Release:
#
# - Continued use of the Software or any Derivative Works derived from it
#   will require you (any any recipients with whom you have shared Derivative
#   Works) to obtain a commercial license within 30 days of the Commercial
#   Release; and
# - If you do not obtain a commercial license within that period, all rights
#   granted under this License automatically terminate, and you must cease use
#   and distribution of the Software and any Derivative Works.
#
# Noting in this License obligates the copyright holder to make a Commercial
# Release, but if/when a Commercial Release occurs, it will be under different
# terms, which may include paid licensing requirements.
#
# 5. Contributions
#
# If you submit, propose, or otherwise contribute bug fixes, features,
# enhancements, documentation, or other materials to the Software 
# ("Contributions"):
#
# - You represent that you have the necessary rights to make the Contributions
#   and that your Contributions do not infringe third-party rights;
# - You agree your Contributions will be made available under the same License
#   as the Software at the time of contribution, without compensation to you;
# - You grant the copyright holder a perpetual, irrevocable, royalty-free,
#   worldwide, non-exclusive license to use, reproduce, modify, distribute,
#   sublicense, and create derivative works from your Contributions, and to
#   include them in the Software and in future versions and distributions;
# - You agree that making a Contribution does not grant you any ownership,
#   co-ownership, or any other rights in or to the Software, any subsequent
#   releases, or any licenses to continue using the Software beyond the rights
#   expressly granted by this License.
#
# 6. Ownership
#
# The Software is licensed, not sold. All rights, title, and interest in and
# to the Software (including all intellectual property rights) are and shall
# remain with the copyright holder and its licensors. Except for the limited
# rights expressly granted herin, no other rights are granted by implciation,
# estoppel, or otherwise.
#
# 7. Warranty Disclaimer
#
# THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND
# NON-INFRINGEMENT. YOU ASSUME ALL RISKS ASSOCIATED WITH THE USE OF THE
# SOFTWARE.
#
# 8. Limitation of Liability
#
# TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR ITS CONTRIBUTORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
# SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF
# PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS INTERRUPTION, ARISING OUT OF
# OR RELATED TO THIS LICENSE OR THE USE OF OR INABILITY TO USE THE SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE TOTAL AGGREGATE
# LIABILITY OF THE COPYRIGHT HOLDER FOR ANY CLAIMS ARISING OUR OF OR RELATING
# TO THIS LICENSE OR THE SOFTWARE SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS
# (UD$100).
#
# 9. Termination
#
# This License automatically terminates if you breach any of its terms or
# upon the conditions described in Section 4. Upon termination, you must
# immediately cease all use and distribution of the Software and Derivative
# Works and destroy all copies in your possession or control. Sections that by
# their nature should survive termination shall survive (including, without
# limitation, Sections 5-8 and 10-12).
#
# 10. Third-Party Components
#
# The Software may include or depend on third-party components that are
# provided under their own licenses. Such licenses govern those components,
# and nothing in this License purports to limit your rights under, or impose
# obligations beyond, the applicable third-party licenses.
#
# 11. Export and Compliance
#
# You are responsible for complying with all applicable laws and regulations,
# including export control laws, in connection with your use of the Software.
#
# 12. Entire Agreement; Changes
#
# This License constitutes the entire agreement between you and the copyright
# holder regarding the Software. The copyright holder may update this License
# for future releases. Your continued use of future releases is subject to the
# then-current license accompanying those releases.
#
# For inquiries about commercial licensing, please contact the copyright
# holder.

name: macOS Builds

on:
  repository_dispatch:
    types: [build-macos-command]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-macos:
    name: Build macOS ARM64
    runs-on: macos-15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Build debug binary
        env:
          CGO_ENABLED: 1
          GOARCH: arm64
          GOOS: darwin
        run: |
          mkdir -p dist/macos-arm64/debug
          go build -v -o dist/macos-arm64/debug/time ./cmd/time

      - name: Build release binary
        env:
          CGO_ENABLED: 1
          GOARCH: arm64
          GOOS: darwin
        run: |
          mkdir -p dist/macos-arm64/release
          go build -v -ldflags="-s -w" -o dist/macos-arm64/release/time ./cmd/time

      - name: Strip debug symbols from release binary
        run: |
          strip dist/macos-arm64/release/time

      - name: Import code signing certificate
        env:
          APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import certificate from secrets
          echo -n "$APPLE_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$APPLE_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Code sign binaries
        env:
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        run: |
          # Sign debug binary
          codesign --force --sign "$APPLE_SIGNING_IDENTITY" \
            --options runtime \
            --timestamp \
            dist/macos-arm64/debug/time

          # Sign release binary
          codesign --force --sign "$APPLE_SIGNING_IDENTITY" \
            --options runtime \
            --timestamp \
            dist/macos-arm64/release/time

          # Verify signatures
          codesign --verify --verbose dist/macos-arm64/debug/time
          codesign --verify --verbose dist/macos-arm64/release/time

      - name: Notarize binaries
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Create zip files for notarization
          cd dist/macos-arm64/debug
          zip time-debug.zip time
          cd ../../../
          
          cd dist/macos-arm64/release
          zip time-release.zip time
          cd ../../../

          # Notarize debug binary
          xcrun notarytool submit dist/macos-arm64/debug/time-debug.zip \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID" \
            --wait

          # Notarize release binary
          xcrun notarytool submit dist/macos-arm64/release/time-release.zip \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID" \
            --wait

          # Remove zip files after notarization
          rm dist/macos-arm64/debug/time-debug.zip
          rm dist/macos-arm64/release/time-release.zip

      # Note: Stapling is not needed for bare executables.
      # The notarization ticket is stored with Apple's servers and will be
      # verified online when the binary is first run by Gatekeeper.

      - name: Clean up keychain
        if: always()
        run: |
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          if [ -f "$KEYCHAIN_PATH" ]; then
            security delete-keychain $KEYCHAIN_PATH
          fi

      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-macos-arm64-debug
          path: dist/macos-arm64/debug/
          if-no-files-found: error

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-macos-arm64
          path: dist/macos-arm64/release/
          if-no-files-found: error
