name: Windows Builds

on:
  repository_dispatch:
    types: [build-windows-command]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-2025
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Build debug binary
        env:
          CGO_ENABLED: 1
        run: |
          New-Item -ItemType Directory -Force -Path dist\windows-x64\debug
          go build -v -o dist\windows-x64\debug\time.exe .\cmd\time
        shell: pwsh

      - name: Build release binary
        env:
          CGO_ENABLED: 1
        run: |
          New-Item -ItemType Directory -Force -Path dist\windows-x64\release
          go build -v -ldflags="-s -w" -o dist\windows-x64\release\time.exe .\cmd\time
        shell: pwsh

      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-windows-x64-debug
          path: dist/windows-x64/debug/
          if-no-files-found: error

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: time-windows-x64
          path: dist/windows-x64/release/
          if-no-files-found: error
